version: '3.1'

services:
  api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:  
      - "3000:3000"
    commmand: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  node_modules: {}   